//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BlogDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Gallery
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> ReadTimes { get; set; }
        public string Tags { get; set; }
        public string SimpleInfo { get; set; }
        public string Cont { get; set; }
        public string MainPicUrl { get; set; }
        public string Source { get; set; }
        public string Type { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<System.DateTime> PubTime { get; set; }
        public string IsPub { get; set; }
        public string ShowType { get; set; }
        public int PosId { get; set; }
        public int Weight { get; set; }
    }
}
